### ISSUE TITLE
Anime: Use a new source

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#157]
`anime` module is down!!

`Hummingbird` is dead (https://medium.com/heykitsu/hummingbird-is-dead-long-live-kitsu-bda6ccfbbcce)
See if `Kitsu` can be used? If not, find a new source.

**Comment by conormag94** [comment]
Hi @swapagarwal I found another API called `Anilist` http://anilist-api.readthedocs.io/en/latest/index.html

It seems like a well documented alternative API you could possibly use?

**Comment by swapagarwal** [comment]
Hey @conormag94, have you played around with the API? We need to identify the right API methods to call in our module.

**Comment by conormag94** [comment]
Hey @swapagarwal I haven't played around with it myself I just noticed it on a reddit post the other day and thought it could be useful.

I don't have the time at the moment to take a look at this but I could come back in 2-3 weeks and have a look at it if no one else has picked it up by then.

**Comment by conormag94** [comment]
Hi @swapagarwal so I've had another look at Kitsu and I think it can be used. Its very new though so there is barely any documentation. I also don't think there is a way to register an application for authentication with Kitsu yet so they provide a public key to use.

Since the `anime` module just searches the old API, I think this Kitsu call can be used to replace it: http://docs.kitsu17.apiary.io/#introduction/json-api/filtering-and-search

I can have a look at replacing the old anime module call to this new API if you like? Then hopefully the api and its documentation will be updated soon.

**Comment by conormag94** [comment]
Submitted a pull request to fix this #166.

**Comment by swapagarwal** [comment]
Hey @conormag94, great work! Thanks to you, the anime module is back up and running. 🎉 
Kudos for diving into Kitsu w/o proper documentation. 😄

**Comment by conormag94** [comment]
No problem @swapagarwal glad I could help 😄
