### ISSUE TITLE
Show specific error messages

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#19]
Right now, whenever an error occurs, a generic error message (`something didn't work as expected`) is displayed to the user, who can't determine what went wrong!

**Comment by shanmukhateja** [comment]
@swapagarwal Have you got any ideas on how to resolve this? I'm thinking of adding a output['error_msg'] in every module's output variable and have it populated with the equivalent error message within the respective modules itself. 

Like say, the query is  
> define something

I sent and just like #43 it throws an error. So now what I'll do, I'll add an additional entry to `output` dict as in `output['error_msg']` to the corresponding **dictionary** module with the message like "_Sorry sir, I couldn't find it's synonym.\n\n Please ask me something else._ " or such similar message. 

This would ensure our commitment towards a "beginners entry" code standard with no additional logic to be added into.

Let me know if you like it so that I can begin implementing this to **all** our modules.

**Comment by swapagarwal** [comment]
@shanmukhateja It's like you read my mind!
I had exactly this in mind while opening this issue but got busy in other things.
If you like, you may go ahead and implement this (for `dictionary` module, as a start).
After that, adding to other modules would be low-hanging fruits! :stuck_out_tongue_winking_eye:

**Comment by shanmukhateja** [comment]
Haha so should I PR the dictionary module first? Come on..let me do them all!

**Comment by shanmukhateja** [comment]
Haha so should I PR the dictionary module first? Come on..let me do them all!

**Comment by swapagarwal** [comment]
btw, how many modules need this? let's first list them down.

**Comment by shanmukhateja** [comment]
I think it's required for all the modules because errors can occur for all modules

**Comment by swapagarwal** [comment]
Agreed, except the basic ones like help, request, etc.
