### ISSUE TITLE
music module is down

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#224]
See https://developer.spotify.com/migration-guide-for-unauthenticated-web-api-calls/
Also, we needed #207 resolved yesterday!

**Comment by edadesd** [comment]
I think we'll need to use the Client Credentials flow, because we don't make requests on behalf of a particular user that require access to that user's account. The Client Credentials flow is explained here: https://developer.spotify.com/web-api/authorization-guide/#client_credentials_flow 

We'll need to add a line for the API key to config.py and rework the module to get an access token, then carry out the request authenticating with the token.

**Comment by edadesd** [comment]
I'm working on this at the moment.
