### ISSUE TITLE
Support for AIML2 - training files

### ISSUE THREAD

**Issue by johndpope** [swapagarwal/JARVIS-on-Messenger#27]
https://github.com/creatorrr/pyAIML

**Comment by swapagarwal** [comment]
Can you give some example(s) showing how can we utilize this?

**Comment by johndpope** [comment]
https://github.com/pandorabots/rosie/tree/master/lib/aiml

**Comment by KartikKannapur** [comment]
@johndpope Thanks for sharing.

AIML seems to take a rule-based approach in building a question-answering system, where most of the responses would have to be hard coded. I think JARVIS would not scale with such a limitation. Also, most of the projects/libraries around AIML are not currently maintained. I suppose we could stick to a text-mining based approach rather than a hard coded rule-based one.

@swapagarwal Your thoughts?

**Comment by swapagarwal** [comment]
Hi @johndpope, I took a look at AIML and I totally agree with @KartikKannapur.
JARVIS aims to learn from human language and respond accordingly. Using AIML will restrict it to a fixed set of queries and scaling it would be quite a tedious task.

**Comment by johndpope** [comment]
I will close this ticket - 
fyi 
<img width="1290" alt="screen shot 2016-05-02 at 7 13 21 pm" src="https://cloud.githubusercontent.com/assets/289994/14970807/0f817cb0-109a-11e6-9b21-6274cba61a7e.png">

https://docs.api.ai/docs/concept-entities#system-entities

**Comment by swapagarwal** [comment]
@johndpope we're using an api.ai alternative, see https://wit.ai/swapagarwal/JARVIS-on-Messenger/
